{{- if .Values.tetragonOperator.metrics.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-operator-metrics
  labels: 
    {{- include "tetragon-operator.labels" . | nindent 4 }}
  spec:
    ports:
      - name: metrics
        port: {{ .Values.tetragonOperator.metrics.port }}
        targetPort: {{ .Values.tetragonOperator.metrics.port }}
        protocol: TCP
    selector:
      {{- include "tetragon-operator.selectorLabels" . | nindent 6 }}
    type: ClusterIP
{{- end }}